analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"

linter:
  rules:
    # Error handling
    avoid_print: false  # We use print for debugging
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    
    # Prevent mock code in production
    avoid_web_libraries_in_flutter: true
    avoid_relative_lib_imports: true
    
    # Code quality
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    
    # Design system enforcement
    # Note: Custom rules for design tokens and localization would need to be implemented
    
    # Flutter specific
    avoid_unnecessary_containers: true
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    
    # Performance
    avoid_function_literals_in_foreach_calls: true
    avoid_renaming_method_parameters: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    discarded_futures: true
    hash_and_equals: true
    null_check_on_nullable_type_parameter: true
    unnecessary_await_in_return: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    use_build_context_synchronously: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_key_in_widget_constructors: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_raw_strings: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_super_parameters: true
    use_test_throws_matchers: true
    use_to_and_as_if_applicable: true
    # use_void_checks: true  # This rule doesn't exist in current Dart linter