analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"

linter:
  rules:
    # Error handling
    avoid_print: false  # We use print for debugging
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    
    # Code quality
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true