name: finally_done
description: "Finally Done - AI-powered personal organization app"
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.4.0
  
  # Local Database
  realm: ^20.2.0  # TODO: Add back when implementing local storage
  
  # HTTP & APIs
  dio: ^5.4.0
  googleapis: ^11.4.0
  googleapis_auth: ^1.6.0
  google_sign_in: ^6.1.5  # Latest version
  url_launcher: ^6.2.5
  
  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  
  # Notifications & Alarms
  flutter_local_notifications: ^16.3.0
  
  # Deep Links
  
  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # Environment variables
  flutter_dotenv: ^5.1.0
  
  # Speech Recognition
  speech_to_text: ^7.0.0
  record: ^4.4.4
  audioplayers: ^6.0.0
  image_picker: ^1.0.7
  
  # Image Processing
  image: ^4.1.7
  
  # Error tracking
  sentry_flutter: ^9.7.0
  
  # Performance Monitoring
  newrelic_mobile: ^1.1.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7

flutter:
  generate: true
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/sounds/
    - .env
    - docs/
  
  # Fonts - Using system fonts for now
  # fonts:
  #   - family: SF Pro Display
  #     fonts:
  #       - asset: assets/fonts/SFProDisplay-Regular.otf
  #       - asset: assets/fonts/SFProDisplay-Bold.otf
  #         weight: 700